### ISSUE TITLE
Document difference/compatibility with Dynamic Active Effects

### ISSUE THREAD

**Issue by Varriount** [krbz999/effectmacro#16]
It would help if this module explained what its differences are when compared to [Dynamic Active Effects](https://foundryvtt.com/packages/dae).

**Comment by krbz999** [comment]
This is a lightweight, system-agnostic module for embedding macros into effects. It also does that one thing only, as intended, while DAE does many other things. This is also only an automation module insofar as you want it to be and can write a macro for it.

The scripts are easier to write for EM than for DAE, as EM does not rely on "args" and is more akin to Item Macro. It is intended to be easy to use, and the details on how can be seen in the readme. It also won't clutter your macro directory because it embeds commands, not just macro names.

I am also told it has more options for macro execution. Macro execution is Effect Macro's singular feature, while DAE has many.

The readme will be used to tell users what _this_ module does, not compare it against others.
