### ISSUE TITLE
[Feature Request] Macro activation when actor with effect is attacked

### ISSUE THREAD

**Issue by ottoh-commits** [krbz999/effectmacro#31]
Hi!

Predefined option for when actor with effect is attacked would be cool (to the selection of Combat started, Combat ended, etc)!  

I am trying macro the Sanctuary spell activation (wisdom saving throw).

**Comment by krbz999** [comment]
Being 'attacked' is system specific. What system would this be for?
Secondly, how is 'being attacked' defined in clear Foundry terms?

**Comment by ottoh-commits** [comment]
Oh sorry, let me add more details. :) 

System is Dnd5e.

What I mean 'being attacked', is that when a creature/enemy is attempting to roll a attack roll on the actor with the effect. Before the attack roll is made, the effects macro activates. I understand that in Dnd5e system there are multiple ways to attack to the actor with the effect and this may be a bit tricky.

**Comment by krbz999** [comment]
Several issues here.
- Rolling an attack "on the actor" is not necessarily applicable, since making an attack roll does not require having a target.
- Executing a script on the target's client _before_ the attack is completed is not possible, since the pre-hook would need to be transmitted to the target's client before the roll is completed - this is axiomatically asynchronous, which the `dnd5e.preRollAttack` hook is not (no hooks are, they cannot be awaited).

An entirely different approach would be needed.

**Comment by ottoh-commits** [comment]
Oh I see. So it would need a change in the system itself. Thanks for the quick responses. :)
